### ISSUE TITLE
Not working on iPhone

### ISSUE THREAD

**Issue by Souness11** [rjstelling/Host.swift#1]
Hello thanks for this example, but its not working on real iPhone.

**Comment by rjstelling** [comment]
Are you getting any output? Or does it fail to return anything? 

Also, what device and OS are you running?

**Comment by rjstelling** [comment]
Have a look at what I've committed today. Should fix most of your issues.

**Comment by Souness11** [comment]
Its working now. Thanks. Im using iPhone 6s and iOS 9.3.1. Do you think that apple approves using this on real app in appstore ?

**Comment by rjstelling** [comment]
I don't see why not. The APIs aren't private and accessing them in Objective-C is very simple. The only issues might be due to the limited IPv6 support (I'm working on).

Let me know if you submit an app that uses it, and I'll start a projects page to list it :)

**Comment by Souness11** [comment]
I try the new commit today and i get 3 IP addresses:

- 127.0.0.1
- 10.216.211.166
- 192.168.0.105 

I run other app on my PC on same wifi and that app give me these addresses:

- 192.168.0.1 -router
- 192.168.0.105 - my iPhone
- 192.168.0.106 - other iPhone
- 192.168.0.104 - my PC
